name: Build Td5 Map Editor
on: [workflow_dispatch] 

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v4

    - name: Install Qt Framework
      uses: jurplel/install-qt-action@v4
      with:
        version: '5.15.2'
        arch: 'win64_mingw81'
        modules: 'qtcharts qtserialport'

    - name: Compile Application
      shell: pwsh
      run: |
        $pro = Get-ChildItem -Filter *.pro -Recurse | Select-Object -First 1
        Set-Location $pro.Directory
        qmake
        mingw32-make release

    - name: Package Executable and DLLs
      shell: pwsh
      run: |
        mkdir $env:GITHUB_WORKSPACE\Td5Editor_Release
        $exe = Get-ChildItem -Filter *.exe -Recurse | Select-Object -First 1
        Copy-Item $exe.FullName -Destination $env:GITHUB_WORKSPACE\Td5Editor_Release\
        $targetExe = "$env:GITHUB_WORKSPACE\Td5Editor_Release\" + $exe.Name
        windeployqt --compiler-runtime $targetExe

    - name: Upload Ready-to-Run App
      uses: actions/upload-artifact@v4
      with:
        name: Td5MapEditor-Windows-Standalone
        path: Td5Editor_Release/
