name: Build Td5 Map Editor
on: [workflow_dispatch] 

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v4

    - name: Install Qt Framework
      uses: jurplel/install-qt-action@v3
      with:
        version: '5.15.2'
        arch: 'win64_mingw81'

    - name: Find and Compile
      shell: pwsh
      run: |
        $proFile = Get-ChildItem -Filter *.pro -Recurse | Select-Object -First 1
        Set-Location $proFile.Directory
        qmake
        mingw32-make release

    - name: Package Executable
      shell: pwsh
      run: |
        Set-Location $env:GITHUB_WORKSPACE
        mkdir Td5Editor_Release
        $exeFile = Get-ChildItem -Filter *.exe -Recurse | Where-Object { $_.FullName -match "release" } | Select-Object -First 1
        Copy-Item $exeFile.FullName -Destination "Td5Editor_Release\Td5MapEditor.exe"
        windeployqt --compiler-runtime "Td5Editor_Release\Td5MapEditor.exe"

    - name: Upload Ready-to-Run App
      uses: actions/upload-artifact@v4
      with:
        name: Td5MapEditor-Windows-Standalone
        path: Td5Editor_Release/
